### ISSUE TITLE
A value type to hold arbitrary JSON5

### ISSUE THREAD

**Issue by callum-oakley** [callum-oakley/json5-rs#3]
We should provide a value type in the style of [serde_json's](https://docs.serde.rs/serde_json/value/enum.Value.html).

Prerequisite for #2.

**Comment by zonyitoo** [comment]
What's the status of this issue?

**Comment by callum-oakley** [comment]
Not started, but will try and find the time to take a look at it in the next few days. Thanks for the reminder!

**Comment by callum-oakley** [comment]
@vdonich alerted me to the fact that `serde_json::Value` works perfectly well with json5, what with serde being interoperable and all.

For example, something like this seems to work absolutely fine:

```rust
let value = json5::from_str::<serde_json::Value>(&buffer);
```

I would still like to address #2 so we can write json5 in a macro, but assuming nobody finds any issues with deserialising in to `serde_json::Value` I think this issue can probably be closed. (@zonyitoo pinging you in case this is still relevant, I realise it was a while ago!)

**Comment by gammelalf** [comment]
There is one edge-case where it does not work:

```rust
use serde::Serialize;
use serde::Deserialize;

#[derive(Serialize, Deserialize)]
struct Example {
    x: f64
}

fn main() {
    let foo = Foo {x: f64::NAN };
    let string = json5::to_string(&foo).unwrap();
    dbg!(&string);
    let value = json5::from_str::<serde_json::Value>(&string).unwrap();
    dbg!(&value);
}
```

Will output:
```
[src/main.rs:12:5] &string = "{\n  x: NaN,\n}"
[src/main.rs:14:5] &value = Object {
    "x": Null,
}
```

`serde_json::Number` (used for the `serde_json::Value::Number` variant) checks the `f64` to be neither `NaN` nor infinite because those are not valid for json, but of course they are valid for json5.

*I don't actually need this feature, but I thought I'd point it out anyway. Feel free to ignore me*
